//* React Query  */
export const QueryKeys = {
    COMMENT: 'COMMENT',
    COMMENT_DETAIL: 'COMMENT_DETAIL',
    POST: 'POST',
    POST_DETAIL: 'POST_DETAIL',
    REPORT_POST: 'REPORT_POST',
    REPORT_POST_DETAIL: 'REPORT_POST_DETAIL',
    REPORT_USER: 'REPORT_USER',
    USER: 'USER',
    USER_DETAIL: 'USER_DETAIL',
    STATISTIC_TAG: 'STATISTIC_TAG',
    STATISTIC_USER: 'STATISTIC_USER'

}